# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.5

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  script:
  - . venv/bin/activate
  - pylint weather_forecast.py
  - python -m unittest -v test_weather_forecast.py
  - coverage run --omit="venv/*" test_weather_forecast.py  # run a coverage test.
  # Omit the other libraries
  - coverage report -m --omit test_weather_forecast.py --fail-under=76 # Display
  # the report, show what was missing, and don't show the coverage of the test cases themselves
  




